"""empty message

Revision ID: 870dd1beacfe
Revises: 
Create Date: 2021-05-22 22:56:32.704105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870dd1beacfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('openid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('openid')
    )
    op.create_table('face_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_id', sa.String(length=50), nullable=False),
    sa.Column('face_img_url', sa.String(length=128), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_id'], ['wechat_info.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouth_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_id', sa.String(length=50), nullable=False),
    sa.Column('symptoms', sa.TEXT(), nullable=True),
    sa.Column('body_type', sa.String(length=10), nullable=True),
    sa.Column('result_img_url', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['wechat_id'], ['wechat_info.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scale_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('sweat', sa.TEXT(), nullable=True),
    sa.Column('pain', sa.TEXT(), nullable=True),
    sa.Column('excretion', sa.TEXT(), nullable=True),
    sa.Column('spirit', sa.TEXT(), nullable=True),
    sa.Column('skin', sa.TEXT(), nullable=True),
    sa.Column('mouth', sa.TEXT(), nullable=True),
    sa.Column('immune', sa.TEXT(), nullable=True),
    sa.Column('breath', sa.TEXT(), nullable=True),
    sa.Column('others', sa.TEXT(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_id'], ['wechat_info.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_id', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('男', '女'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_id'], ['wechat_info.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('scale_info')
    op.drop_table('mouth_info')
    op.drop_table('face_info')
    op.drop_table('wechat_info')
    # ### end Alembic commands ###
